cit: test_rest_endpoint: update 'Assembled At' field name
Summary:
# Description
cit: rest endpoint, update Assembled At field name

following fboss-lite wedge_eeprom library updated
https://github.com/facebook/openbmc/commit/283b1a5ba94573be70d722ea2af3916e254c4c95

# Motivation
to fix the issue, CIT failure on the known good unit.

```
======================================================================
FAIL: test_endpoint_api_sys_mb_fruid (tests.montblanc.test_rest_endpoint.RestEndpointTest.test_endpoint_api_sys_mb_fruid) (attrib='Assembled at')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/common/base_rest_endpoint_test.py", line 155, in verify_endpoint_attributes
    self.assertIn(
AssertionError: 'Assembled at' not found in '{"Information": {"Version": "5", "Product Name": "MINIPACK3", "Product Part Number": "30100032", "System Assembly Part Number": "", "Meta PCBA Part Number": "132100032", "Meta PCB Part Number": "131100011", "ODM/JDM PCBA Part Number": "R3214G001202", "ODM/JDM PCBA Serial Number": "A122224210041", "Product Production State": "2", "Product Version": "1", "Product Sub-Version": "0", "Product Serial Number": "F502224220059", "System Manufacturer": "CLS", "System Manufacturing Date": "20240610", "PCB Manufacturer": "GCE", "Assembled At": "CTH", "EEPROM location on Fabric": "FCB", "BMC MAC Base": "b4:db:91:95:52:7e", "BMC MAC Address Size": "1", "Switch ASIC MAC Base": "b4:db:91:95:52:7f", "Switch ASIC MAC Address Size": "138", "CRC16": "0x1c95 (CRC Matched)"}, "Actions": [], "Resources": []}' : endpoint /api/sys/mb/fruid missing attrib Assembled at

----------------------------------------------------------------------
Ran 64 tests in 165.140s

FAILED (failures=1, skipped=3)
```

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1817

Test Plan:
Test on Montblanc DVT Platform
[cit-test.txt](https://github.com/user-attachments/files/18071463/cit-test.txt)

Reviewed By: mikechoifb

Differential Revision: D67004768

Pulled By: alandau

fbshipit-source-id: dc62bb3298dbf724ac4eb3c71b8f41b43c49c9f7